name: Docker Image CI

on: 
  branches:
    - master
  # repository_dispatch:
  #   types: 
  #     - deploy_docker

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOCKER_URL: https://registry.hub.docker.com/v1/repositories/abaplint/abaplint
      NPM_URL: https://registry.npmjs.org/abaplint
    steps:
    - uses: actions/checkout@v2
    - name: Detect version change
      id: detect_version_change
      run: |
        LAST_DOCKER_TAG=`curl -sS $DOCKER_URL/tags | jq '.[]["name"]' | tr -d '"' | grep -Po "(\d+\.)+\d+" | sort --version-sort | tail -1`
        LAST_NPM_VERSION=`curl -sS $NPM_URL | jq '.time | to_entries[] | .key' | tr -d '"' | grep -Po "(\d+\.)+\d+" | sort --version-sort | tail -1`
        echo Last docker version: $LAST_DOCKER_TAG
        echo Last npm version: $LAST_NPM_VERSION
        if [ "$LAST_DOCKER_TAG" != "$LAST_NPM_VERSION" ]; then
          echo "::set-output name=VERSION_CHANGED::yes"
          echo "::set-output name=NEW_VERSION::$LAST_NPM_VERSION"
        fi
    - name: Build and publish docker container
      if: success() && steps.detect_version_change.outputs.VERSION_CHANGED == 'yes'
      env:
        DOCKER_USERNAME: larshp
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      uses: docker/build-push-action@v1
      with:
        username: ${{ DOCKER_USERNAME }}
        password: ${{ DOCKER_PASSWORD }}
        registry: myregistry
        repository: abaplint/abaplint
        tags: latest, ${{ steps.detect_version_change.outputs.NEW_VERSION }}
