name: Docker Image CI

on: 
  repository_dispatch:
    types: 
      - deploy_docker

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: bin/build-container.sh
    - name: Deploy Docker image
      run: bin/push-containers.sh --dryrun
